/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as CoreCompetenciesRouteImport } from './routes/core-competencies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientExperienceRouteImport } from './routes/client-experience'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreCompetenciesRoute = CoreCompetenciesRouteImport.update({
  id: '/core-competencies',
  path: '/core-competencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientExperienceRoute = ClientExperienceRouteImport.update({
  id: '/client-experience',
  path: '/client-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-experience': typeof ClientExperienceRoute
  '/contact': typeof ContactRoute
  '/core-competencies': typeof CoreCompetenciesRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-experience': typeof ClientExperienceRoute
  '/contact': typeof ContactRoute
  '/core-competencies': typeof CoreCompetenciesRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-experience': typeof ClientExperienceRoute
  '/contact': typeof ContactRoute
  '/core-competencies': typeof CoreCompetenciesRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/client-experience'
    | '/contact'
    | '/core-competencies'
    | '/industries'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/client-experience'
    | '/contact'
    | '/core-competencies'
    | '/industries'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/client-experience'
    | '/contact'
    | '/core-competencies'
    | '/industries'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClientExperienceRoute: typeof ClientExperienceRoute
  ContactRoute: typeof ContactRoute
  CoreCompetenciesRoute: typeof CoreCompetenciesRoute
  IndustriesRoute: typeof IndustriesRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-competencies': {
      id: '/core-competencies'
      path: '/core-competencies'
      fullPath: '/core-competencies'
      preLoaderRoute: typeof CoreCompetenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-experience': {
      id: '/client-experience'
      path: '/client-experience'
      fullPath: '/client-experience'
      preLoaderRoute: typeof ClientExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClientExperienceRoute: ClientExperienceRoute,
  ContactRoute: ContactRoute,
  CoreCompetenciesRoute: CoreCompetenciesRoute,
  IndustriesRoute: IndustriesRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
